# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8636a867153f8ffb03696c63f71c4ea5183406299ab4116dab05e8a312d0c3abb9e27364d490be9c56cc21c90ee4e9fb9a0e6e51e13e4784dd01fd54fcb87aa1

test:
  secret_key_base: 831d0b9555e9628300d129a875e22c7b190e945d931dea7d3552ddccf5295f3b9bb3ae88b0b10500711374a7cd0b353dfa2d348658ab944c346e082fcdb97ced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
